### ISSUE TITLE
Mac: superuser required for brew & make in setup

### ISSUE THREAD

**Issue by alexkogon** [bbaassssiiee/buildserver#17]
I had to use sudo for the following commands in the setup for Mac OSX:

brew install --upgrade ansible
brew install caskroom/cask/brew-cask
brew cask install --upgrade virtualbox
brew cask install --upgrade vagrant

make install

maybe you want to make a note of that in the README

**Comment by bbaassssiiee** [comment]
It is custom nowadays on mac to change ownership for brew, so you don't need sudo.

chown -R alex /usr/local


On 24 Aug 2015, at 10:49, Alex Kogon <notifications@github.com> wrote:

I had to use sudo for the following commands in the setup for Mac OSX:

brew install --upgrade ansible
brew install caskroom/cask/brew-cask
brew cask install --upgrade virtualbox
brew cask install --upgrade vagrant

make install

maybe you want to make a note of that in the README

**Comment by alexkogon** [comment]
Ah ok. Does that apply to 'make install' as well?

I don't mind using sudo when I need to, just thought it would be nice to be able to copy/paste the commands :)

**Comment by bbaassssiiee** [comment]
'make install' should not need sudo. If it it asks for permission it might be that you did not 'brew install python' and use OSX python. That is not a good idea because Apple wipes python extensions on upgrade.


On 24 Aug 2015, at 11:00, Alex Kogon <notifications@github.com> wrote:

Ah ok. Does that apply to 'make install' as well?

I don't mind using sudo when I need to, just thought it would be nice to be able to copy/paste the commands :)

**Comment by bbaassssiiee** [comment]
I just found out Roland extended the scope of 'make install'


On 24 Aug 2015, at 11:11, Bas Meijer <bas.meijer@me.com> wrote:

'make install' should not need sudo. If it it asks for permission it might be that you did not 'brew install python' and use OSX python. That is not a good idea because Apple wipes python extensions on upgrade.


On 24 Aug 2015, at 11:00, Alex Kogon <notifications@github.com <mailto:notifications@github.com>> wrote:

Ah ok. Does that apply to 'make install' as well?

I don't mind using sudo when I need to, just thought it would be nice to be able to copy/paste the commands :)

**Comment by alexkogon** [comment]
No I didn't 'brew install python' because it wasn't in the instructions; should it be?

I just tried to do so and I get this error:

Mac-mini:buildserver alex$ sudo brew install python
Password:
Error: python-2.7.8_2 already installed
To install this version, first `brew unlink python'

should I unlink and overwrite it?

**Comment by bbaassssiiee** [comment]
If you don't have strong convictions about python, then it is best to upgrade to Python 2.7.10 with brew upgrade python

**Comment by alexkogon** [comment]
I haven't the remotest of convictions about python, as I never write it so as long as it works.

Don't know if this affects your script at all, maybe you should mention it in the README if so

**Comment by alexkogon** [comment]
you may want to mention something about how brew should be changed to not require superuser in the README – i did it all with sudo but now have to run all the ansible commands with sudo too which is not ideal. i'll try redoing on another box but don't want to start over this takes a long time to d/l all the images anyhow...
